### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by ManuelLoaizaV** [ManuelLoaizaVasquez/inf263-algoritmia-pucp#7]
- [x] 621: Task Scheduler
- [x] 56: Merge Intervals
- [x] 350: Intersection of Two Arrays II
- [x] 15: 3Sum
- [x] 10: Regular Expression Matching
- [x] 674: Longest Continuous Increasing Subsequence
- [x] 121: Best Time to Buy and Sell Stock
- [x] 314: Binary Tree Vertical Order Traversal
- [x] 69: Sqrt(x)
- [x] 257: Binary Tree Paths
- [ ] 51: N-Queens
- [ ] 42: Trapping Rain Water
- [ ] 173: Binary Search Tree Iterator
- [x] 151: Reverse Words in a String
- [ ] 43: Multiply Strings
- [ ] 38: Count and Say
- [ ] 273: Integer to English Words
- [ ] 91: Decode Ways
- [ ] 138: Copy List with Random Pointer
- [ ] 283: Move Zeroes
- [ ] 236: Lowest Common Ancestor of a Binary Tree
- [ ] 253: Meeting Rooms II
- [ ] 449: Serialize and Deserialize BST
- [ ] 133: Clone Graph
- [ ] 49: Group Anagrams
- [ ] 31: Next Permutation
- [ ] 339: Nested List Weight Sum
- [ ] 29: Divide Two Integers
- [ ] 114: Flatten Binary Tree to Linked List
- [ ] 301: Remove Invalid Parentheses
- [ ] 1: Two Sum
- [ ] 98: Validate Binary Search Tree
- [ ] 88: Merge Sorted Array
- [ ] 242: Valid Anagram
- [ ] 642: Design Search Autocomplete System
- [ ] 139: Word Break
- [ ] 560: Subarray Sum Equals K
- [ ] 212: Word Search II
- [ ] 297: Serialize and Deserialize Binary Tree
- [ ] 102: Binary Tree Level Order Traversal
- [ ] 325: Maximum Size Subarray Sum Equals k
- [ ] 378: Kth Smallest Element in a Sorted Matrix
- [ ] 348: Design Tic-Tac-Toe
- [ ] 4: Median of Two Sorted Arrays
- [ ] 278: First Bad Version
- [ ] 76: Minimum Window Substring
- [ ] 65: Valid Number
- [ ] 32: Longest Valid Parentheses
- [ ] 8: String to Integer (atoi)
- [ ] 215: Kth Largest Element in an Array
- [ ] 772: Basic Calculator III
- [ ] 17: Letter Combinations of a Phone Number
- [ ] 567: Permutation in String
- [ ] 5: Longest Palindromic Substring
- [ ] 636: Exclusive Time of Functions
- [ ] 349: Intersection of Two Arrays
- [ ] 295: Find Median from Data Stream
- [ ] 13: Roman to Integer
- [ ] 380: Insert Delete GetRandom O(1)
- [ ] 277: Find the Celebrity
- [ ] 282: Expression Add Operators
- [ ] 122: Best Time to Buy and Sell Stock II
- [ ] 341: Flatten Nested List Iterator
- [ ] 285: Inorder Successor in BST
- [ ] 44: Wildcard Matching
- [ ] 20: Valid Parentheses
- [ ] 270: Closest Binary Search Tree Value
- [ ] 57: Insert Interval
- [ ] 67: Add Binary
- [ ] 680: Valid Palindrome II
- [ ] 200: Number of Islands
- [ ] 3: Longest Substring Without Repeating Characters
- [ ] 146: LRU Cache
- [ ] 158: Read N Characters Given Read4 II - Call multiple times
- [ ] 125: Valid Palindrome
- [ ] 157: Read N Characters Given Read4
- [ ] 127: Word Ladder
- [ ] 211: Add and Search Word - Data structure design
- [ ] 34: Find First and Last Position of Element in Sorted Array
- [ ] 477: Total Hamming Distance
- [ ] 111: Minimum Depth of Binary Tree
- [ ] 23: Merge k Sorted Lists
- [ ] 37: Sudoku Solver
- [ ] 336: Palindrome Pairs
- [ ] 249: Group Shifted Strings
- [ ] 694: Number of Distinct Islands
- [ ] 124: Binary Tree Maximum Path Sum
- [ ] 543: Diameter of Binary Tree
- [ ] 22: Generate Parentheses
- [ ] 468: Validate IP Address
- [ ] 105: Construct Binary Tree from Preorder and Inorder Traversal
- [ ] 235: Lowest Common Ancestor of a Binary Search Tree
- [ ] 206: Reverse Linked List
- [ ] 438: Find All Anagrams in a String
- [ ] 317: Shortest Distance from All Buildings
- [ ] 9: Palindrome Number
- [ ] 252: Meeting Rooms
- [ ] 126: Word Ladder II
- [ ] 304: Range Sum Query 2D - Immutable
- [ ] 247: Strobogrammatic Number II
- [ ] 209: Minimum Size Subarray Sum
- [ ] 143: Reorder List
- [ ] 399: Evaluate Division
- [ ] 647: Palindromic Substrings
- [ ] 11: Container With Most Water
- [ ] 128: Longest Consecutive Sequence
- [ ] 227: Basic Calculator II
- [ ] 145: Binary Tree Postorder Traversal
- [ ] 2: Add Two Numbers
- [ ] 785: Is Graph Bipartite?
- [ ] 50: Pow(x, n)
- [ ] 825: Friends Of Appropriate Ages
- [ ] 53: Maximum Subarray
- [ ] 381: Insert Delete GetRandom O(1) - Duplicates allowed
- [ ] 21: Merge Two Sorted Lists
- [ ] 238: Product of Array Except Self
- [ ] 387: First Unique Character in a String
- [ ] 81: Search in Rotated Sorted Array II
- [ ] 408: Valid Word Abbreviation
- [ ] 688: Knight Probability in Chessboard
- [ ] 494: Target Sum
- [ ] 103: Binary Tree Zigzag Level Order Traversal
- [ ] 239: Sliding Window Maximum
- [ ] 162: Find Peak Element
- [ ] 241: Different Ways to Add Parentheses
- [ ] 437: Path Sum III
- [ ] 94: Binary Tree Inorder Traversal
- [ ] 113: Path Sum II
- [ ] 110: Balanced Binary Tree
- [ ] 75: Sort Colors
- [ ] 129: Sum Root to Leaf Numbers
- [ ] 46: Permutations
- [ ] 445: Add Two Numbers II
- [ ] 691: Stickers to Spell Word
- [ ] 246: Strobogrammatic Number
- [ ] 721: Accounts Merge
- [ ] 28: Implement strStr()
- [ ] 347: Top K Frequent Elements
- [ ] 33: Search in Rotated Sorted Array
- [ ] 286: Walls and Gates
- [ ] 208: Implement Trie (Prefix Tree)
- [ ] 78: Subsets
- [ ] 14: Longest Common Prefix
- [ ] 79: Word Search
- [ ] 269: Alien Dictionary
- [ ] 300: Longest Increasing Subsequence
- [ ] 678: Valid Parenthesis String
- [ ] 19: Remove Nth Node From End of List
- [ ] 74: Search a 2D Matrix
- [ ] 210: Course Schedule II
- [ ] 230: Kth Smallest Element in a BST
- [ ] 26: Remove Duplicates from Sorted Array
- [ ] 224: Basic Calculator
- [ ] 218: The Skyline Problem
- [ ] 415: Add Strings
- [ ] 689: Maximum Sum of 3 Non-Overlapping Subarrays
- [ ] 73: Set Matrix Zeroes
- [ ] 670: Maximum Swap
- [ ] 39: Combination Sum
- [ ] 140: Word Break II
- [ ] 36: Valid Sudoku
- [ ] 68: Text Justification
- [ ] 112: Path Sum
- [ ] 791: Custom Sort String
- [ ] 311: Sparse Matrix Multiplication
- [ ] 549: Binary Tree Longest Consecutive Sequence II
- [ ] 496: Next Greater Element I
- [ ] 47: Permutations II
- [ ] 435: Non-overlapping Intervals
- [ ] 498: Diagonal Traverse
- [ ] 12: Integer to Roman
- [ ] 505: The Maze II
- [ ] 523: Continuous Subarray Sum
- [ ] 7: Reverse Integer
- [ ] 340: Longest Substring with At Most K Distinct Characters
- [ ] 161: One Edit Distance
- [ ] 159: Longest Substring with At Most Two Distinct Characters
- [ ] 692: Top K Frequent Words
- [ ] 207: Course Schedule
- [ ] 463: Island Perimeter
- [ ] 824: Goat Latin
- [ ] 266: Palindrome Permutation
- [ ] 398: Random Pick Index
- [ ] 597: Friend Requests I: Overall Acceptance Rate
- [ ] 443: String Compression
- [ ] 844: Backspace String Compare
- [ ] 490: The Maze
- [ ] 393: UTF-8 Validation
- [ ] 104: Maximum Depth of Binary Tree
- [ ] 332: Reconstruct Itinerary
- [ ] 24: Swap Nodes in Pairs
- [ ] 199: Binary Tree Right Side View
- [ ] 394: Decode String
- [ ] 419: Battleships in a Board
- [ ] 153: Find Minimum in Rotated Sorted Array
- [ ] 426: Convert Binary Search Tree to Sorted Doubly Linked List
- [ ] 489: Robot Room Cleaner
- [ ] 767: Reorganize String
- [ ] 298: Binary Tree Longest Consecutive Sequence
- [ ] 308: Range Sum Query 2D - Mutable
